
DROP TABLE IF EXISTS review_like;
DROP TABLE IF EXISTS review_dislike;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films_genres;
DROP TABLE IF EXISTS mpa_films;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS mpa_ratings;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS directors;
DROP TABLE IF EXISTS films_directors;


CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    login VARCHAR (100) NOT NULL,
    birthday DATE,
    email VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS friendships (
    user_id_who_send INT,
    user_id_to_whom_send INT,
    status varchar (20),
    FOREIGN KEY (user_id_who_send) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id_to_whom_send) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id_who_send, user_id_to_whom_send)
);

CREATE TABLE IF NOT EXISTS genres (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200),
    description VARCHAR(200),
    duration INT,
    release_date DATE,
    rating INT
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INT,
    genre_id INT,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS mpa_ratings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar (15) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa_films (
    film_id INT,
    mpa_rating INT,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    FOREIGN KEY (mpa_rating) REFERENCES mpa_ratings (id),
    PRIMARY KEY (film_id, mpa_rating)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INT,
    film_id INT,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    film_id INTEGER NOT NULL,
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL DEFAULT TRUE,
    useful INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_film_id FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_like (
    review_id INTEGER,
    user_id INTEGER,
    CONSTRAINT fk_review_like_review_id FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_like_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_dislike (
    review_id INTEGER,
    user_id INTEGER,
    CONSTRAINT fk_review_dislike_review_id FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_dislike_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS directors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name varchar(50)
);

CREATE TABLE IF NOT EXISTS films_directors (
    director_id INTEGER,
    film_id INTEGER,
    FOREIGN KEY (director_id) REFERENCES directors (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (director_id, film_id)
);